### ISSUE TITLE
how to develop skill (api )

### ISSUE THREAD

**Issue by jachenms** [StreetLamb/tribe#109]
### Privileged issue

- [X] I'm @StreetLamb or he asked me directly to create an issue here.

### Issue Content

I am working on the multiagent development, need to add more skill , presales -skill ( product demo, technical discussion, proposal preparing ) , marketing manager （  event arrangement, leads collection ..）, so how to develop the API in tribe？

**Comment by StreetLamb** [comment]
Hi @jachenms, please take a look at the [skills section of the readme](https://github.com/StreetLamb/tribe?tab=readme-ov-file#skills). If you are just making an API call, go to the Skills page > click the 'Add Skill' button > define your skill definition. However, for more complex skills, you need to write the code for it.
