### ISSUE TITLE
how to extend the conservation limit 

### ISSUE THREAD

**Issue by jachenms** [StreetLamb/tribe#110]
### Privileged issue

- [X] I'm @StreetLamb or he asked me directly to create an issue here.

### Issue Content

![image](https://github.com/user-attachments/assets/931fcbd0-8066-47d0-88d8-5bd64941008c)
  how to reset the limit ?

**Comment by StreetLamb** [comment]
Hi @jachenms , thanks for raising. By default, the recursion limit is set to 25. I will add a feature to configure it from the UI.

**Comment by StreetLamb** [comment]
Hi @jachenms, you can configure the `RECURSION_LIMIT` from the .env file in the latest release. Resolved in #118
