### ISSUE TITLE
Bug: Failed to delete thread after updating to Enhanced Postgres Checkpointer

### ISSUE THREAD

**Issue by Onelevenvy** [StreetLamb/tribe#120]
### Privileged issue

- [X] I'm @StreetLamb or he asked me directly to create an issue here.

### Issue Content

When attempting to delete a thread, an error occurs. The error message is shown in the image below：
<img width="863" alt="image" src="https://github.com/user-attachments/assets/545e2a38-2594-474a-ad1b-4018c2778143">

> sqlalchemy.exc.IntegrityError: (psycopg.errors.ForeignKeyViolation) update or delete on table "thread" violates foreign key constraint "checkpoint_blobs_thread_id_fkey" on table "checkpoint_blobs"
DETAIL:  Key (id)=(cbf3db6a-1323-4b74-a0c0-db4edf02c9de) is still referenced from table "checkpoint_blobs".
[SQL: DELETE FROM thread WHERE thread.id = %(id)s::UUID]
[parameters: {'id': 'cbf3db6a-1323-4b74-a0c0-db4edf02c9de'}]

We might need to modify the code at "tribe/backend/app/api/routes/threads.py-@router.delete("/{id}")": to fix the issue."

**Comment by StreetLamb** [comment]
@Onelevenvy Thanks for reporting! Will check it out.

**Comment by StreetLamb** [comment]
Issue should be resolved!
