### ISSUE TITLE
Port conflict issue

### ISSUE THREAD

**Issue by jachenms** [StreetLamb/tribe#92]
### Privileged issue

- [X] I'm @StreetLamb or he asked me directly to create an issue here.

### Issue Content

![image](https://github.com/user-attachments/assets/cd573165-e100-410f-a307-b8ba00415c73)
 how  to solve the issue port conflict

**Comment by StreetLamb** [comment]
Hi @jachenms , likely it is due to your port 80 being used by another service. You need to stop the other service first. Try running `lsof -i tcp:80` and then `kill -9 <PID>` if you want to stop the service using port 80.

**Comment by StreetLamb** [comment]
@jachenms, I'm closing this issue. Please reopen if you are still experiencing it.
